madara pr
Skittyblock/aidoku-community-sources pull request #21
Opened 2022-05-25 14:31 UTC by pandeynmn

madara end game

2022-05-25 14:36 UTC, Skittyblock requested changes
https://github.com/Skittyblock/aidoku-community-sources/pull/20#pullrequestreview-984911126

2022-05-25 15:39 UTC, beerpiss reviewed
Format your JSONs:
```sh
# oneliner that formats all jsons in current directory and sub-directories
# requires jq and moreutils
find . -type f -name '*.json' -print0 | xargs -0 -I% sh -c "jq . % | unexpand -t2 | sponge %"
```

2022-05-26 14:18 UTC, pandeynmn commented
> [#20 (review)](https://github.com/Skittyblock/aidoku-community-sources/pull/20#pullrequestreview-984911126)

Fixed #20 issues

2022-05-28 16:02 UTC, Skittyblock approved these changes

2022-05-28 16:03 UTC, merged