new source: zh.manhuaren
Skittyblock/aidoku-community-sources pull request #212
Opened 2023-02-14 01:00 UTC by Trzeth

Note:
- clean up #82 

Checklist:
- [x] Updated source's version for individual source changes
- [x] Updated all sources' versions for template changes
- [x] Set appropriate `nsfw` value
- [x] Did not change `id` even if a source's name or language were changed
- [x] Tested the modifications by running it on the simulator or a test device

2023-02-14 15:39 UTC, Skittyblock requested changes
thanks for reviving a dead pr, here are some more changes
- use tabs for json formatting
- try not to create your own StringRefs just to read them into a rust string (inefficient)
- don't use `i32_to_string`
- don't unwrap (use expect instead if you're sure it'll never fail unless site changes)
- use `Default::default()` for struct default values

2023-02-14 15:39 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/helper.rs
> +pub fn encode_uri(string: String) -> String {
is there a reason you can't use `encode_uri` from aidoku-rs helpers crate?
```toml
[dependencies]
aidoku = { git = "https://github.com/Aidoku/aidoku-rs", features = ["helpers"] }
```
then
```rs
use aidoku::helpers::uri::encode_uri_component;
```

2023-02-14 15:39 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/helper.rs
> +pub fn i32_to_string(mut integer: i32) -> String {
use alloc ToString instead

2023-02-14 15:39 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +		.unwrap_or_else(|_| StringRef::from(""))
it's not very good to do this. something better would be
```rs
let category_str = match manga.get("mangaTheme").as_string() {
	Ok(str) => str.read(),
	Err(_) => String::new(),
};

2023-02-14 15:39 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +				.read(),
if it will never be empty, you could just `.expect("error message if it doesn't exist")` it

2023-02-14 15:39 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +			categories: Vec::new(),
instead of doing this, use `..Default::default()` at the end of the struct to fill in unused properties with default values

2023-02-14 15:39 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +				let ch_obj = ch.as_object().unwrap();
```suggestion
				let ch_obj = ch.as_object().expect("chapter item should be object");
```
or equivalent error message

2023-02-14 15:39 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +					text: String::new(),
`..Default::default()`

2023-02-15 23:20 UTC, Skittyblock commented
Yeah checking if it's empty is fine, but you don't need to match, you just can just do an if
```rs
if str.is_empty() {
	fallback
} else {
	str
}
```

The default function is fine, yeah, but you should probably name them something different since `unwrap_or_default` is used when something has the default trait implemented, and the `unwrap_or_empty` function unwraps or returns the fallback, not an empty string, so the name is a little misleading.

2023-02-16 00:47 UTC, Trzeth commented
Done. 😊

2023-02-17 02:03 UTC, Skittyblock commented
json still using spaces for indentation, make sure it's tabs

2023-02-17 02:18 UTC, Trzeth commented
something wrong with vscode builtin formatter, fixed now.

2023-02-17 23:20 UTC, Skittyblock approved these changes

2023-02-17 23:21 UTC, merged