fix: nettruyen
Skittyblock/aidoku-community-sources pull request #290
Opened 2023-04-07 22:23 UTC by jckli

Checklist:
- [ ] Updated source's version for individual source changes
- [ ] Updated all sources' versions for template changes
- [ ] Set appropriate `nsfw` value
- [ ] Did not change `id` even if a source's name or language were changed
- [ ] Tested the modifications by running it on the simulator or a test device 

just to fix for @vus.#6370 lol
cheers
![FaWtyz7agAAZxdP](https://user-images.githubusercontent.com/39673993/230686107-98839392-c859-4206-9b64-c94cdf2b0dd4.jpg)

2023-04-08 01:20 UTC, beerpiss requested changes
otherwise just clean up the lint warnings

2023-04-08 01:20 UTC, beerpiss commented on src/rust/wpcomics/sources/nettruyen/res/source.json
> +  	]
tabs instead of 4 spaces thanks

2023-04-08 01:32 UTC, jckli commented
> otherwise just clean up the lint warnings

fuck me why do I have to clean up lint I changed 1 STRING

2023-04-11 21:40 UTC, Skittyblock commented on src/rust/wpcomics/sources/nettruyen/res/source.json
> +  	"listings": [
why did you add spaces :uhh:

2023-04-14 19:45 UTC, Skittyblock approved these changes

2023-04-14 19:46 UTC, merged