nepnep: sort feature and refactor a lot of things
Skittyblock/aidoku-community-sources pull request #295
Opened 2023-04-09 19:50 UTC by yongsu-l

Had to do a decent amount of refactor so I could use `Vec` sort features. Couldn't use &str for deserialized struct values since serde requires ownership for string values with [escaped values](https://github.com/serde-rs/serde/issues/1413#issuecomment-494892266). I also couldn't use `Cow` since we don't have it in aidoku-rs

Checklist:
- [x] Updated source's version for individual source changes
- [x] Updated all sources' versions for template changes
- [x] Set appropriate `nsfw` value
- [x] Did not change `id` even if a source's name or language were changed
- [x] Tested the modifications by running it on the simulator or a test device

2023-04-10 00:49 UTC, beerpiss commented
> I also couldn't use Cow since we don't have it in aidoku-rs

You could pull in the `alloc` crate:

```rust
extern crate alloc;

use alloc::borrow::Cow;

// moo
```

https://doc.rust-lang.org/alloc/borrow/enum.Cow.html

2023-04-10 01:00 UTC, beerpiss requested changes
looks okay though i havent tested it

2023-04-10 02:19 UTC, yongsu-l commented on src/rust/en.nepnep/src/lib.rs
> +                }
sg - I know you could do something like `MyEnum.values()[idx]` in java but what can you do in rust? i was thinking of implementing a fn which has a mapping

2023-04-10 04:50 UTC, yongsu-l commented on src/rust/en.nepnep/src/lib.rs
> +                }
nvm - I found some examples in aidoku-rs using From trait

2023-05-21 19:58 UTC, Skittyblock commented on src/rust/en.nepnep/src/ls
what is this

2023-06-04 19:58 UTC, yongsu-l commented on src/rust/en.nepnep/src/ls
lul

2023-08-07 04:40 UTC, Skittyblock approved these changes
sorry forgot to review this

2023-08-07 04:40 UTC, merged