done
Skittyblock/aidoku-community-sources pull request #312
Opened 2023-04-19 19:04 UTC by aphronyx

Close: #280

Checklist:
- [x] Updated source's version for individual source changes
- [x] Set appropriate `nsfw` value
- [x] Did not change `id` even if a source's name or language were changed
- [x] Tested the modifications by running it on the simulator or a test device

2023-04-20 20:11 UTC, Skittyblock requested changes

2023-04-20 20:11 UTC, Skittyblock commented on src/rust/zh.baozimanhua/res/filters.json
> +]
add a newline at the end

2023-04-20 20:11 UTC, Skittyblock commented on src/rust/zh.baozimanhua/res/source.json
> +}
add a newline

2023-04-20 20:11 UTC, Skittyblock commented on src/rust/zh.baozimanhua/src/lib.rs
> +	request.header("Referer", BASE_URL).header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_3_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36");
I would move this to a constant `USER_AGENT` and then import it in parser.rs since you use it multiple times

2023-04-20 20:11 UTC, Skittyblock commented on src/rust/zh.baozimanhua/src/parser.rs
> +		let id = url.split('/').last().unwrap().to_string();
don't use `unwrap`

2023-04-20 20:12 UTC, Skittyblock commented
also run `cargo +nightly fmt` and `cargo +nightly clippy` and fix the warnings

2023-04-23 16:32 UTC, Skittyblock commented
I think you need to delete Cargo.lock and recompile, you might be on an old aidoku-rs version

2023-04-26 05:20 UTC, aphronyx commented
> I think you need to delete Cargo.lock and recompile, you might be on an old aidoku-rs version

Done!

2023-05-03 00:41 UTC, Skittyblock commented
run `chmod +x build.sh` (or equivalent) to make the build script executable for the ci

2023-05-03 05:36 UTC, aphronyx commented
> run `chmod +x build.sh` (or equivalent) to make the build script executable for the ci

Done!

2023-05-12 21:04 UTC, Skittyblock approved these changes

2023-05-12 21:08 UTC, merged