add source: prismascans
Skittyblock/aidoku-community-sources pull request #468
Opened 2023-09-27 07:07 UTC by julioreigen

<h2> Changes </h2>

Add a new madara source: [Prisma Scans](https://prismascans.net/) (PT-BR)

<h2> Checklist </h2>

- [x] Updated source's version for individual source changes
- [x] Set appropriate `nsfw` value
- [x] Did not change `id` even if a source's name or language were changed
- [x] Tested the modifications by running it on the simulator or a test device 

<h2>Screenshots <h2>

| Source info | Browse | Filters |
|--|--| -- |
|  <img src="https://i.imgur.com/oM0OMTw.png" alt="source info" width="200"/>|<img src="https://i.imgur.com/ImF2J7n.jpg" alt="browse" width="200"/>  |<img src="https://i.imgur.com/5e7jREC.png" alt="filters" width="200"/>  |

|  Search | Manhwa | Chapter |
|--|--| -- |
|  <img src="https://i.imgur.com/QTBZysc.png" alt="search tab" width="200"/>|<img src="https://i.imgur.com/f90jAaK.png" alt="manhwa tab" width="200"/>  |<img src="https://i.imgur.com/HYY9Ro6.png" alt="browse" width="200"/>  |

2023-10-01 15:38 UTC, Skittyblock requested changes

2023-10-01 15:38 UTC, Skittyblock commented on src/rust/madara/sources/prismascans/res/filters.json
> +				"name": "OnGoing"
```suggestion
				"name": "Ongoing"
```

2023-10-01 15:38 UTC, Skittyblock commented on src/rust/madara/sources/prismascans/res/source.json
> +	]
```suggestion
	}
```

2023-10-01 15:38 UTC, Skittyblock commented on src/rust/madara/sources/prismascans/src/lib.rs
> +	data
should just be able to do this
```suggestion
	template::MadaraSiteData {
		base_url: String::from("https://prismascans.net"),
		description_selector: String::from("div.summary_content_wrap div p"),
		alt_ajax: true,
		..Default::default()
	}
```

2023-10-01 15:38 UTC, Skittyblock commented on src/rust/madara/sources/prismascans/res/Icon.png
This should have a background, not transparent

2023-10-01 15:38 UTC, Skittyblock commented on src/rust/madara/sources/prismascans/res/source.json
> +		"nsfw": 1
```suggestion
		"nsfw": 2
```

2023-10-01 16:30 UTC, julioreigen commented
The website is under maintenance at the moment, when it comes back I will see if the source will still be working

2023-10-04 15:17 UTC, Skittyblock approved these changes

2023-10-04 15:18 UTC, merged