Asura URL Update #3
Skittyblock/aidoku-community-sources pull request #470
Opened 2023-09-30 18:51 UTC by General-Mudkip

Gotta love Asura

2023-09-30 18:54 UTC, General-Mudkip commented
No idea why it's referencing #3 but I'll create a new PR if needed

2023-09-30 20:12 UTC, KaBankz commented
> No idea why it's referencing #3 but I'll create a new PR if needed

Remove `#3` from your pr title

2023-10-01 15:16 UTC, Skittyblock requested changes
can you remove the trailing slashes from the URLs?

2023-10-04 15:14 UTC, Skittyblock approved these changes

2023-10-04 15:14 UTC, merged