chore(assortedscans): update icon
Skittyblock/aidoku-community-sources pull request #506
Opened 2023-11-07 13:46 UTC by ObserverOfTime

Checklist:
- [x] Updated source's version for individual source changes
- [ ] Updated all sources' versions for template changes
- [ ] Set appropriate `nsfw` value
- [ ] Did not change `id` even if a source's name or language were changed
- [ ] Tested the modifications by running it on the simulator or a test device

2023-11-12 23:57 UTC, Skittyblock requested changes
Version needs to be updated in the `source.json` so that Aidoku recognizes it as a source update.

2023-11-13 09:00 UTC, ObserverOfTime commented
I knew I'd missed something…

2023-11-22 15:02 UTC, ObserverOfTime commented
Done.

2023-11-24 17:23 UTC, Skittyblock approved these changes

2023-11-24 17:27 UTC, merged