Migrate old PrismaScans to DemonSect
Skittyblock/aidoku-community-sources pull request #511
Opened 2023-11-16 02:35 UTC by julioreigen

**Info:**
PrismaScans changed their scan name and website url, so I updated the aidoku source to work correctly.
I put source version in 1, since it's like a new source.
New URL: [demonsect.com.br](https://demonsect.com.br)

**Checklist:**
- [x] Updated source's version for individual source changes
- [x] Set appropriate `nsfw` value
- [x] Did not change `id` even if a source's name or language were changed
- [x] Tested the modifications by running it on the simulator or a test device

2023-11-24 17:25 UTC, Skittyblock requested changes

2023-11-24 17:25 UTC, Skittyblock commented on src/rust/madara/sources/demonsect/res/source.json
> +}
Make sure there are newlines at the end of files
```suggestion
}

```

2023-11-24 22:29 UTC, Skittyblock commented
Source doesn't seem work for me so I can't to test it

2023-11-25 17:08 UTC, julioreigen commented
> Source doesn't seem to work for me so I can't test it

So I'm going to close this PR and make two others: One to delete PrismaScan and another to add DemonSect source.

2023-11-25 17:25 UTC, Skittyblock commented
Uhh I don't think making two different PRs will fix anything. You can just make your changes here on this PR.

2023-11-25 17:27 UTC, julioreigen commented
@Skittyblock I checked the font's website and it looks like it went into maintenance on the 23rd of this month and is redirecting to discord, which is why the source isn't working now.
I will let you know when the site is back online so you can check the source.

2023-12-06 12:39 UTC, dodieboy commented
I believe it is back online

2023-12-06 12:48 UTC, julioreigen commented
Yeah, it's back and all the manga have only the last chapters released, it's not a source problem.

2024-01-05 20:59 UTC, julioreigen commented
@Skittyblock I updated the source and now it's fully working!
Tested on my iphone.

2024-01-07 07:36 UTC, Skittyblock approved these changes
I personally still can't access the site, but the code looks fine and if it works for you then it's probably good to go.

2024-01-07 07:37 UTC, merged

2024-01-07 12:47 UTC, julioreigen commented
> I personally still can't access the site, but the code looks fine and if it works for you then it's probably good to go.

Probably they are denying access from IPs outside brazil.