Add Comick.fun source
Skittyblock/aidoku-community-sources pull request #53
Opened 2022-07-18 23:05 UTC by daarkdemon

Checklist:
- [ ] Updated source's version for individual source changes
- [ ] Updated all sources' versions for template changes
- [ ] Set appropriate `nsfw` value
- [ ] Did not change `id` even if a source's name or language were changed
- [ ] Tested the modifications by running it on the simulator or a test device

2022-07-25 16:10 UTC, beerpiss reviewed
some thoughts
- I don't really understand the point of filtering by one translation group only?
- Add final newlines to your files
- Run your code through `cargo fmt`

2022-07-25 16:10 UTC, beerpiss commented on src/rust/multi.comick/build.sh
> +mv package.aix ../../../package.aix
add final newline

2022-07-25 16:10 UTC, beerpiss commented on src/rust/multi.comick/res/settings.json
> +
remove the empty lines

2022-07-25 16:10 UTC, beerpiss commented on src/rust/multi.comick/res/settings.json
> +		"footer": "NOTE: This will apply to all the manga in this source",
```suggestion
		"footer": "Show translations from this group only. This will apply to all manga in this source.",
```

2022-07-25 16:10 UTC, beerpiss commented on src/rust/multi.comick/res/settings.json
> +				"placeholder": "Show translation from this group only"
```suggestion
				"placeholder": "Group Name"
```

2022-07-25 16:10 UTC, beerpiss commented on src/rust/multi.comick/res/source.json
> +		{ "name": "New"}
```suggestion
		{ "name": "New" }
```

2022-07-25 16:10 UTC, beerpiss commented on src/rust/multi.comick/src/parser.rs
> +	}else{
```suggestion
	} else {
```

2022-07-25 16:10 UTC, beerpiss commented on src/rust/multi.comick/src/parser.rs
> +		let url =  get_search_url(api_url, title, included_tags, excluded_tags, demographic_tags, manga_type, sort_by, completed, page);
```suggestion
		let url = get_search_url(api_url, title, included_tags, excluded_tags, demographic_tags, manga_type, sort_by, completed, page);
```

2022-07-25 16:13 UTC, beerpiss requested changes

2022-07-25 16:13 UTC, beerpiss commented on src/rust/multi.comick/src/parser.rs
> +		url: format!("{}/comic/{}", String::from("https://comick.fun"), id),
```suggestion
		url: format!("https://comick.fun/comic/{}", id),
```

2022-07-25 23:26 UTC, daarkdemon commented
>j

2022-07-25 23:28 UTC, daarkdemon commented
> * I don't really understand filtering by a single translation group, especially when it's not done on the API side.
 - As it simple to view all single chapters and the user may have preferred choices

2022-07-27 13:40 UTC, beerpiss commented
> > * I don't really understand filtering by a single translation group, especially when it's not done on the API side.
> 
> * As it simple to view all single chapters from one group and the user may have preferred choices

Users may forget that they've set a preferred scanlator and wonder why their manga have no chapters though. I think it's better to leave the job of filtering scanlators to Aidoku to implement in the future.

2022-07-31 13:25 UTC, daarkdemon commented
> > > * I don't really understand filtering by a single translation group, especially when it's not done on the API side.
> > 
> > 
> > 
> > * As it simple to view all single chapters from one group and the user may have preferred choices
> 
> Users may forget that they've set a preferred scanlator and wonder why their manga have no chapters though. I think it's better to leave the job of filtering scanlators to Aidoku to implement in the future.

Ok,
Removed filtering scanlation group

2022-10-09 20:04 UTC, daarkdemon commented
Any update on this ?

2022-11-17 02:42 UTC, Skittyblock requested changes
you're using `?` way too much. this is bad because it just returns an error when it's actually recoverable. just provide default values or handle the errors without returning.

2022-11-17 02:42 UTC, Skittyblock commented on src/rust/multi.comick/build.sh
> +mv package.aix ../../../package.aix
this wasn't resolved

2022-11-17 02:42 UTC, Skittyblock commented on src/rust/multi.comick/res/source.json
> +		{ "name": "New"}
still not fixed

2022-11-17 02:42 UTC, Skittyblock commented on src/rust/multi.comick/src/parser.rs
> +	std::String,
```suggestion
	error::Result, prelude::format, std::net::HttpMethod, std::net::Request, std::String, std::Vec,
```

2022-11-17 02:42 UTC, Skittyblock commented on src/rust/multi.comick/src/parser.rs
> +				let cover = data_obj.get("cover_url").as_string()?.read();
you should `continue` if any of these don't exist, rather than using `?` and returning.

2022-11-17 02:42 UTC, Skittyblock commented on src/rust/multi.comick/src/parser.rs
> +	let viewer = match data.get("country").as_string()?.read().as_str() {
don't use `?`

2022-11-17 02:42 UTC, Skittyblock commented on src/rust/multi.comick/src/parser.rs
> +		let chapter_obj = chapter.as_object()?;
if this doesn't work, `continue` instead of using `?`

2022-11-17 02:42 UTC, Skittyblock commented on src/rust/multi.comick/src/parser.rs
> +					let page_url = image_obj.get("url").as_string()?.read();
`continue` instead

2023-01-06 05:28 UTC, closed without merging

2023-01-06 20:18 UTC, Skittyblock commented
replaced by #143