feat(suryatoon): create new source
Skittyblock/aidoku-community-sources pull request #563
Opened 2024-01-22 18:29 UTC by Kareylo

Checklist:
- [x] Updated source's version for individual source changes
- [x] Updated all sources' versions for template changes
- [x] Set appropriate `nsfw` value
- [x] Did not change `id` even if a source's name or language were changed
- [x] Tested the modifications by running it on the simulator or a test device

2024-01-23 10:08 UTC, Skittyblock requested changes
- icon should be fully opaque (add a background)
- filters.json should use tabs for indentation

2024-01-23 12:08 UTC, Kareylo commented
> * icon should be fully opaque (add a background)
> 
>     * filters.json should use tabs for indentation

Should be fine now

2024-01-25 09:20 UTC, Skittyblock commented
icon still isn't fully opaque -- looks like you flood filled the outside and it didn't fill behind the slightly transparent pixels surrounding the logo. you should overlay it on top of a white square or export it with a background color from photoshop or whatever tool

2024-01-29 12:29 UTC, Skittyblock approved these changes

2024-01-29 12:29 UTC, merged