fix:(Suryatoon): Chapter pages not loading + Icon
Skittyblock/aidoku-community-sources pull request #590
Opened 2024-02-26 19:27 UTC by Kareylo

Checklist:
- [x] Updated source's version for individual source changes
- [x] Updated all sources' versions for template changes
- [x] Set appropriate `nsfw` value
- [x] Did not change `id` even if a source's name or language were changed
- [x] Tested the modifications by running it on the simulator or a test device

2024-02-26 19:55 UTC, Kareylo commented
Fixed the `shared reference of mutable static is discouraged` on the template, should be nice for next releases of the template

2024-03-03 09:23 UTC, Skittyblock requested changes
you didn't change anything that would really affect the rest of the sources (just resolved a warning), so it doesn't make sense to bump the versions of all of them I don't think

2024-03-03 11:00 UTC, Kareylo commented
> you didn't change anything that would really affect the rest of the sources (just resolved a warning), so it doesn't make sense to bump the versions of all of them I don't think

Sounds logic to me.

2024-03-04 09:41 UTC, Skittyblock approved these changes

2024-03-04 09:42 UTC, merged