new source: webtoonxyz
Skittyblock/aidoku-community-sources pull request #602
Opened 2024-03-03 22:00 UTC by Aeonss

Checklist:
- [ ] Updated source's version for individual source changes
- [ ] Updated all sources' versions for template changes
- [ ] Set appropriate `nsfw` value
- [ ] Did not change `id` even if a source's name or language were changed
- [ ] Tested the modifications by running it on the simulator or a test device

2024-03-03 23:08 UTC, Aeonss commented
build.sh should have the right permissions (-rwxrwxr-x), but is still failing to build.

2024-03-07 09:06 UTC, Skittyblock requested changes
make sure to run `cargo +nightly fmt`

2024-03-07 09:06 UTC, Skittyblock commented on src/rust/en.webtoonxyz/res/source.json
> +		"nsfw": 1
honestly it looks like primarily nsfw stuff to me
```suggestion
		"nsfw": 2
```

2024-03-07 09:06 UTC, Skittyblock commented on src/rust/en.webtoonxyz/src/parser.rs
> +
```suggestion
```

2024-03-07 09:06 UTC, Skittyblock commented on src/rust/en.webtoonxyz/src/parser.rs
> +
```suggestion
```

2024-03-07 09:06 UTC, Skittyblock commented on src/rust/en.webtoonxyz/src/parser.rs
> +		//let date_updated = chapter.select(".chapter-release-date").text().as_date("dd MMM YYYY", Some("en_US"), None);
```suggestion
```

2024-03-07 09:06 UTC, Skittyblock commented on src/rust/en.webtoonxyz/src/parser.rs
> +		let id = String::from(id[5]);
I don't think you need to collect this into a vec before selecting a single index, but I can't quite recall how to do it. maybe with skip or something

2024-03-07 09:06 UTC, Skittyblock commented on src/rust/en.webtoonxyz/src/parser.rs
> +}
```suggestion
}

```

2024-03-07 19:01 UTC, Aeonss commented on src/rust/en.webtoonxyz/res/Icon.png
Upscaled the favicon with AI, it should look better now

2024-03-09 05:51 UTC, Skittyblock commented
Oh wait, I just looked at the website and realized it's a madara site. There isn't any reason to add a whole new source, you can just add it to the madara template.

2024-03-21 14:07 UTC, Aeonss commented
> Oh wait, I just looked at the website and realized it's a madara site. There isn't any reason to add a whole new source, you can just add it to the madara template.

This PR is ready to be reviewed again

2024-03-23 07:24 UTC, Skittyblock requested changes

2024-03-23 07:24 UTC, Skittyblock commented on src/rust/madara/template/src/template.rs
> +			use_user_agent: false,
instead of having a bool to use one built in `USER_AGENT`, this should be a `Option<String>` that defaults to `None`

2024-03-23 07:24 UTC, Skittyblock commented on src/rust/madara/template/src/template.rs
> +			search_cookies: String::from("wpmanga-adult=1"),
why did you change this? pretty sure it's supposed to be `wpmanga-adault=1`

2024-03-23 07:24 UTC, Skittyblock commented on src/rust/madara/template/src/template.rs
> +	aidoku::prelude::println!("urL: {}", url);
don't keep these in final builds

2024-03-23 07:24 UTC, Skittyblock commented on src/rust/madara/template/src/helper.rs
> +	if let Ok(html) = Request::new(url.as_str(), HttpMethod::Get).header("User-Agent", USER_AGENT).html() {
shouldn't it only use the user agent if the source specifies that it should?

2024-03-25 03:00 UTC, shiroyasha9 commented
I have addressed the comments left by Skitty in this PR - https://github.com/Aeonss/aidoku-community-sources/pull/3
Please take a look guys and let me know if it needs any changes. 

This was my first rust project, so looking forward (things you do for manga/manhwa) 😆

2024-03-26 09:50 UTC, Skittyblock approved these changes

2024-03-26 09:51 UTC, merged