Updated baseurl and chapter selector
Skittyblock/aidoku-community-sources pull request #615
Opened 2024-03-19 16:40 UTC by Aeonss

Checklist:
- [ ] Updated source's version for individual source changes
- [ ] Updated all sources' versions for template changes
- [ ] Set appropriate `nsfw` value
- [ ] Did not change `id` even if a source's name or language were changed
- [ ] Tested the modifications by running it on the simulator or a test device 

fixes one of the issues described in https://github.com/Skittyblock/aidoku-community-sources/issues/613

2024-03-23 07:37 UTC, Skittyblock requested changes
Even though the old url redirects to thunderscans, keiyoushi seems to have migrated ozulscans to kingofmanga (https://github.com/keiyoushi/extensions-source/pull/1917). 

Regardless, if we change Ozul Scans to either of them, the name and icon and url should all be changed, not just the url used inside the source.

2024-03-25 19:04 UTC, Aeonss commented
> Even though the old url redirects to thunderscans, keiyoushi seems to have migrated ozulscans to kingofmanga ([keiyoushi/extensions-source#1917](https://github.com/keiyoushi/extensions-source/pull/1917)).
> 
> Regardless, if we change Ozul Scans to either of them, the name and icon and url should all be changed, not just the url used inside the source.

It seems that OzulScans redirects to Thunderscans, but king-of manga is still a distinctly different website. Do you want me to use https://king-ofmanga.com/ instead of https://thunderscans.com/ and follow keiyoushi?

2024-03-27 09:24 UTC, Skittyblock commented on src/rust/mangastream/sources/ozulscans/res/source.json
> +		"url": "https://thunderscans.com/"
```suggestion
		"url": "https://thunderscans.com"
```

2024-03-27 09:24 UTC, Skittyblock approved these changes

2024-03-27 09:28 UTC, merged