feat: add libgroup template and mangalib source
Skittyblock/aidoku-community-sources pull request #634
Opened 2024-04-13 14:08 UTC by vlapsk1y

Checklist:
- [x] Updated source's version for individual source changes
- [x] Updated all sources' versions for template changes
- [x] Set appropriate `nsfw` value
- [x] Did not change `id` even if a source's name or language were changed
- [x] Tested the modifications by running it on the simulator or a test device 

I know about this pq (#176), but it's not merged into main branch and soon stay deprecated, because mangalib.me in the near future get very major update (test-front.mangalib.me). The new version of mangalib has become unparseable and open at browser as web app.

2024-04-14 09:43 UTC, Skittyblock requested changes
- jsons should use tabs for indentation 
- files should have trailing newlines
- run `cargo +nightly fmt`
- I'm not sure about the "site id" stuff, especially since you're only adding mangalib. the template struct should probably just provide the url and route and stuff, with the actual sources containing the stuff rather than the template hardcoding it.

2024-04-14 09:43 UTC, Skittyblock commented on src/rust/multi.libgroup/template/src/parser.rs
> +            })
use `..Default::default` at the end of the struct and exclude the fields you don't populate
```suggestion
            arr_manga.push(Manga {
                id,
                cover,
                title,
                url,
                status,
                nsfw: MangaContentRating::Safe,
                viewer: aidoku::MangaViewer::Rtl,
                ..Default::default
            })
```

2024-04-14 13:32 UTC, vlapsk1y commented
as for "site id", I wanted to make the task easier for those who want to implement other sites of libgroup. Although them still need to edit template, cuz nsfw sites has own cdn. I really didn't knew about that fact, until checked before writing the comment.

2024-04-25 08:01 UTC, Skittyblock commented
yes but the point of the template is to contain all things specific to the template that the individual websites use, but then it's the job of the actual sources to just use the template while providing the source specific things. for example, the individual source should be able to give any base url to the template, and the template shouldn't need to know which exact source it is.

2024-04-25 14:20 UTC, vlapsk1y commented
I understood your point, I'll make a commit in the next days. thanks u.

2024-04-28 03:26 UTC, Skittyblock commented on src/rust/multi.libgroup/sources/mangalib/res/filters.json
jsons are still using spaces for indentation instead of tabs

2024-04-28 03:35 UTC, Skittyblock commented
icon should be 128x128 and make sure to fix the warnings clippy generates when running `cargo +nightly clippy`, but after that it should be good

2024-05-02 10:07 UTC, Skittyblock commented on src/rust/multi.libgroup/sources/mangalib/res/filters.json
ids need to be strings

2024-05-03 09:17 UTC, Skittyblock approved these changes

2024-05-03 09:18 UTC, merged