feat(GenZToons): Removing SuryaToons - Adding GenZToons
Skittyblock/aidoku-community-sources pull request #757
Opened 2024-09-09 16:57 UTC by Kareylo

As Surya Toons is now dead, I removed it.
The new Team name of Surya Toons is GenZ Toons.

Still the same template,

Checklist:
- [ x] Updated source's version for individual source changes
- [ x] Updated all sources' versions for template changes
- [ x] Set appropriate `nsfw` value
- [ x] Did not change `id` even if a source's name or language were changed
- [ x] Tested the modifications by running it on the simulator or a test device

2024-09-16 13:54 UTC, Skittyblock requested changes
do the sources have the same content and ids? if so, it would be better to keep the old id and just change the name and bump the version. if not though, this is fine

2024-09-16 13:54 UTC, Skittyblock commented on src/rust/mangastream/sources/genztoons/res/source.json
> +		"url": "https://genztoons.com/",
base url shouldn't have a trailing slash -- didn't catch this for suryatoon I guess
```suggestion
		"url": "https://genztoons.com",
```

2024-09-22 17:23 UTC, Kareylo commented
> do the sources have the same content and ids? if so, it would be better to keep the old id and just change the name and bump the version. if not though, this is fine

It seems it's exactly same content and ids, I switched back to old source id and bumped the version

2024-09-22 17:54 UTC, Skittyblock approved these changes

2024-09-22 17:54 UTC, merged