Add new mangastream sources, fix Manga Titles ManhwaIndo & Manhwaland.
Skittyblock/aidoku-community-sources pull request #78
Opened 2022-08-17 19:40 UTC by naufaljct48

Fix:
- ManhwaIndo & Manhwaland Manga Title Trim

New:
- Add new Indonesian sources: MangKomik & MasterKomik

Checklist:
- [ ] Updated source's version for individual source changes
- [ ] Updated all sources' versions for template changes
- [x] Set appropriate `nsfw` value
- [x] Did not change `id` even if a source's name or language were changed
- [x] Tested the modifications by running it on the simulator or a test device

2022-08-18 03:01 UTC, Skittyblock requested changes
I think these sources contain some adult content, so nsfw value should be 1.

2022-08-18 03:01 UTC, Skittyblock commented on src/rust/mangastream/sources/mangkomik/res/source.json
> +		"version": 1,
```suggestion
		"version": 1,
		"nsfw": 1,
```

2022-08-18 07:56 UTC, naufaljct48 commented
> I think these sources contain some adult content, so nsfw value should be 1.

okay fixed

2022-08-18 15:53 UTC, Skittyblock approved these changes

2022-08-19 14:15 UTC, Skittyblock approved these changes

2022-08-19 14:16 UTC, merged