fix(komga): Non-English search not working
Skittyblock/aidoku-community-sources pull request #782
Opened 2024-10-20 14:24 UTC by dyphire

Close #659

Checklist:
- [x] Updated source's version for individual source changes
- [x] Updated all sources' versions for template changes
- [x] Set appropriate `nsfw` value
- [x] Did not change `id` even if a source's name or language were changed
- [x] Tested the modifications by running it on the simulator or a test device

2024-10-20 20:50 UTC, Skittyblock requested changes
make sure you fix the clippy warning. 

this still works for searches containing special characters like & and spaces, correct?

2024-10-21 06:15 UTC, dyphire commented
> make sure you fix the clippy warning.

Changed as suggested by clippy.

> this still works for searches containing special characters like & and spaces, correct?

Searching for special characters has never worked correctly because komga doesn't do url decoding on the search response. That's why non-English searches didn't work before, because aidoku encodes the url and komga doesn't decode the url accordingly. This is a limitation of komga.

2024-10-22 15:21 UTC, dyphire commented
> Any more questions here?

Here, too.

2024-11-08 19:11 UTC, Skittyblock approved these changes

2024-11-08 19:11 UTC, merged