fix(asurascans): fix chapter names and page list parsing
Skittyblock/aidoku-community-sources pull request #804
Opened 2024-11-19 02:55 UTC by AlokSwaminathan

Checklist:
- [x] Updated source's version for individual source changes
- [x] Updated all sources' versions for template changes
- [x] Set appropriate `nsfw` value
- [x] Did not change `id` even if a source's name or language were changed
- [x] Tested the modifications by running it on the simulator or a test device

2024-11-19 03:01 UTC, Skittyblock requested changes
make sure clippy passes; i think it will give you some error about the indentation in lib.rs

edit: i guess clippy passed in the workflow? make sure the file is properly indented though

2024-11-19 03:01 UTC, Skittyblock commented on src/rust/en.asurascans/src/lib.rs
> +      let end = text_slice.find(".webp").unwrap();
don't use `unwrap`, if it doesn't exist either continue or return early with an error

2024-11-19 03:09 UTC, AlokSwaminathan commented
I had some space based tabbing on accident, I think that's fixed now.

2024-11-24 15:53 UTC, Skittyblock approved these changes
i guess we can have this as a temporary fix

2024-11-24 15:53 UTC, merged