Add source zh.manhuaren
Skittyblock/aidoku-community-sources pull request #82
Opened 2022-09-13 02:14 UTC by geniusgordon

Checklist:
- [ ] Updated source's version for individual source changes
- [ ] Updated all sources' versions for template changes
- [ ] Set appropriate `nsfw` value
- [ ] Did not change `id` even if a source's name or language were changed
- [ ] Tested the modifications by running it on the simulator or a test device

2022-09-18 19:08 UTC, hyspace commented
Hi, what is being blocked？

2022-09-19 01:38 UTC, hyspace commented
It seems like the icon is not transparent lol

2022-11-17 13:44 UTC, Skittyblock requested changes
also make sure to run `cargo +nightly clippy` for other changes you should make, and `cargo +nightly fmt` to correct some formatting.

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/helper.rs
> +	print(&temp);
best not to leave print statements in

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/helper.rs
> +	print(gsn);
remove

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/helper.rs
> +	req.string()
could one-line this

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +	print(format(format_args!("sort: {}", sort)));
remove

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +}
there are no listings, so this doesn't need to be implemented. just remove it.

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +	print(&qs);
remove

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +	print(&url);
remove

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +	// print(&body);
remove

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +		.unwrap_or_else(|_| StringRef::from(""))
I think you can just do this?
```suggestion
		.unwrap_or(StringRef::from(""))
```

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +			.unwrap_or_else(|_| StringRef::from("-"))
these should use empty strings if they don't exist, not "-"

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +	// print(&body);
remove prints

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +fn get_page_list(manga_id: String, chapter_id: String) -> Result<Vec<Page>> {
remove prints

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +}
these don't need to be implemented

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +fn get_manga_list_by_filter(filter: ListFilter, page: i32) -> Result<MangaPageResult> {
remove prints

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +				.unwrap_or_else(|_| StringRef::from("-"))
again, use empty strings here instead

2022-11-17 13:44 UTC, Skittyblock commented on src/rust/zh.manhuaren/src/lib.rs
> +				// print(&url);
remove

2023-02-17 23:21 UTC, Skittyblock commented
replaced by #212

2023-02-17 23:21 UTC, closed without merging